CREATE TABLE BUY
(
	NUM NUMBER(3) PRIMARY KEY,
	ID VARCHAR2(10),
	GOODS VARCHAR2(15),
	PRICE NUMBER(7),
	QT NUMBER(3),
	BDATE DATE
);

CREATE TABLE PAY
(
	PNUM NUMBER(3) PRIMARY KEY,
	NUM NUMBER(3) REFERENCES BUY(NUM),
	AMOUNT NUMBER(8),
	METHOD VARCHAR2(8)
);

CREATE SEQUENCE BUY_SEQ;
CREATE SEQUENCE PAY_SEQ;

CREATE OR REPLACE TRIGGER IN_BUY
AFTER INSERT ON BUY
FOR EACH ROW
BEGIN
	INSERT INTO PAY VALUES(PAY_SEQ.NEXTVAL,:NEW.NUM,:NEW.PRICE*:NEW.QT,'TMP');
END;
/

CREATE OR REPLACE TRIGGER UP_BUY
AFTER UPDATE ON BUY
FOR EACH ROW
BEGIN
	UPDATE PAY SET AMOUNT=:NEW.PRICE*:NEW.QT WHERE NUM=:NEW.NUM;
END;
/

CREATE OR REPLACE TRIGGER DE_BUY
BEFORE DELETE ON BUY
FOR EACH ROW
BEGIN
	DELETE FROM PAY WHERE NUM=:OLD.NUM;
END ;
/
